#!/bin/bash

# Script which performs cleanup of files in the runtime environment in
# preparation for bundling.  This performs various tasks such as removing
# unneeded files, stripping binaries, etc.
set -x

GAP_ROOT_RUNTIME="$1"
GAP_ROOT="$2"

cd "$GAP_ROOT_RUNTIME"
ls
echo $(pwd)

rm -f packages*tar*
rm -rf .git

# Strip debug symbols from exes and dlls, saving hundreds of MB
find . -type f \( -name '*.exe' -o -name '*.dll' -o -name '*.a' -o -name '*.o' -o -name '*.so' \) \
    -exec strip -g {} \;

rm -f ../../run-gap.sh

echo "#!/usr/bin/env bash" > ../../run-gap.sh
echo "stty susp undef # disable ctrl-z" >> ../../run-gap.sh
echo 'cd $(cygpath --mydocs)' >> ../../run-gap.sh
echo "${GAP_ROOT}/gap" >> ../../run-gap.sh
