#!/bin/bash

# Script which performs cleanup of files in the runtime environment in
# preparation for bundling.  This performs various tasks such as removing
# unneeded files, stripping binaries, etc.
#
# The one thing it does not do is to run rebase; this needs to be done using a
# subcyg shell see the $(SAGE_ROOT_RUNTIME) target in the Makefile.
set -x

SAGE_ROOT_RUNTIME="$1"
SAGE_ROOT="$2"

cd "$SAGE_ROOT_RUNTIME"
ls
echo $(pwd)

rm -f packages*tar*
rm -rf .git

# Strip debug symbols from exes and dlls, saving hundreds of MB
find . -type f \( -name '*.exe' -o -name '*.dll' -o -name '*.a' -o -name '*.o' -o -name '*.so' \) \
    -exec strip -g {} \;

rm -f ../../run-gap.sh

echo "#!/usr/bin/env bash" > ../../run-gap.sh
echo 'cd $(cygpath --mydocs)' >> ../../run-gap.sh
echo "${SAGE_ROOT}/gap" >> ../../run-gap.sh

rm -f ../../gapicon.ico
cp cnf/cygwin/gapicon.ico ../../gapicon.ico