name: GAP Windows release

# Based on https://github.com/mit-plv/fiat-crypto/blob/master/.github/workflows/coq-windows.yml
on:
  push:
  pull_request:

env:
  CHERE_INVOKING: 1

jobs:
  build:
    name: Make Cygwin ${{ matrix.arch }} installer
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        gapbranch:
          - master

    steps:
    - run: choco install InnoSetup

    - uses: actions/checkout@v2

    - uses: gap-actions/setup-cygwin-for-gap@v1

    - name: Compile GAP and download packages
      run: bash release_gap.sh ARCH=${{ matrix.arch }} SAGE_VERSION=${{ matrix.gapbranch }}
      shell: C:\cygwin64\bin\bash.exe --login -o igncr '{0}'

    - name: Upload release
      uses: actions/upload-artifact@v2
      with:
        name: GAP Windows installer - ${{ matrix.arch }}
        path: Output/*
