name: GAP Windows release

# Based on https://github.com/mit-plv/fiat-crypto/blob/master/.github/workflows/coq-windows.yml
on:
  push:
  pull_request:

env:
  CHERE_INVOKING: 1

jobs:
  build:
    name: Make Cygwin ${{ matrix.arch }} installer
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        gapbranch:
          - master

    steps:
    - run: choco install InnoSetup

    # clone GAP repository
    # TODO: should instead create or download a recent release snapshot tarball
    - uses: actions/checkout@v4
      with:
        repository: gap-system/gap
        path: gap-${{ matrix.gapbranch }}
        ref: ${{ matrix.gapbranch }}

    # clone the gap-windows repository
    - uses: actions/checkout@v4
      with:
        path: gap-windows

    - uses: gap-actions/setup-cygwin@v1

    - name: Compile GAP and download packages
      shell: C:\cygwin64\bin\bash.exe --login --norc -o igncr '{0}'
      run: |
        cd gap-${{ matrix.gapbranch }} && ./autogen.sh && cd ..
        cd ${GITHUB_WORKSPACE}/gap-windows
        bash release_gap.sh
      env:
        ARCH: ${{ matrix.arch }}
        GAP_VERSION: ${{ matrix.gapbranch }}

    - name: Upload release
      uses: actions/upload-artifact@v4
      with:
        name: GAP Windows installer - ${{ matrix.arch }}
        path: Output/*
